### PR TITLE
Add QuickSight endpoints

### PR DESCRIPTION
**Pull request by riiwo**
List compiled according to AWS QuickSight availability in [regions]

[regions]: https://docs.aws.amazon.com/quicksight/latest/user/regions.html

### CODE REVIEW

**Review by s22su — APPROVED** [review]

**Review by zidik — APPROVED** [review]
Double-checked the list - looks good!

**Comment by zidik** [comment]
Now PR to original lib?

**Comment by riiwo** [comment]
> Now PR to original lib?

There is already one: https://github.com/ex-aws/ex_aws/pull/793

**Comment by s22su** [comment]
@riiwo can probably close it and delete our fork?

**Pull request closed without merging**
